added onhttprequest event hook to enable blazor support
launchdarkly/dotnet-eventsource pull request #85
Opened 2022-03-03 13:55 UTC by acquleo

A OnHttpRequest event is raised before the request in order to be able to execute the SetBrowserResponseStreamingEnabled method on a Blazor app client.

2022-03-08 22:43 UTC, eli-darkly requested changes
Providing a hook for general modification of request attributes is a reasonable feature. However, I think the `event` pattern is not a great fit for this. All of the other events defined on `EventSource` are for _notifications_ of things that have happened— not for making changes to the behavior of `EventSource`. And an `event` inherently can have any number of handlers, which isn't a good fit for this feature since the ordering of event handler calls is not well defined but the ordering of changes to an HTTP request could be significant.

So, instead of exposing an `event` for this, I would rather provide a `ConfigurationBuilder` setter: `RequestModifier(Action<HttpRequestMessage>)`. If this hook is non-null, it is called by `EventSourceService` at the same place that you are currently calling `OnHttpRequest?.Invoke`.

2022-03-09 09:48 UTC, acquleo commented
I've modified the code according to your proposal.

2022-03-09 17:51 UTC, eli-darkly commented on src/LaunchDarkly.EventSource/Configuration.cs
> +
Minor: extra blank lines here.

2022-03-09 17:52 UTC, eli-darkly commented on src/LaunchDarkly.EventSource/Configuration.cs
> +        /// Delegate hook invoked before an http request has been performed.
```suggestion
        /// Delegate hook invoked before an HTTP request has been performed.
```

2022-03-09 17:52 UTC, eli-darkly commented on src/LaunchDarkly.EventSource/ConfigurationBuilder.cs
> +        /// Sets a delegate hook invoked before an http request has been performed.
```suggestion
        /// Sets a delegate hook invoked before an HTTP request has been performed, allowing changes to the request.
```

2022-03-09 17:52 UTC, eli-darkly commented on src/LaunchDarkly.EventSource/EventSource.cs
> +
Extra blank line.

2022-03-09 17:54 UTC, eli-darkly requested changes

2022-03-09 17:54 UTC, eli-darkly commented on src/LaunchDarkly.EventSource/LaunchDarkly.EventSource.csproj
> +    <AssemblyOriginatorKeyFile>../../LaunchDarkly.EventSource.snk</AssemblyOriginatorKeyFile>
I don't know why this change was made, but please revert it. We do not want the assembly to be strong-named in _every_ configuration, but only in the Release configuration, as is specified on line 33 of this file. Possibly your IDE made this change automatically for some reason, but please be careful that you're not checking in unintended changes to the project configuration.

2022-03-10 07:37 UTC, acquleo reviewed
agree with your comments

2022-04-01 23:06 UTC, merged

2022-04-19 19:08 UTC, eli-darkly commented
This feature is now in the 4.2.0 release. Sorry it took so long for us to get back to it.